config/routes.rb
Showgeeks::Application.routes.draw do

  # We need to define devise_for just omniauth_callbacks otherwise it does not work with scoped locales
  # see https://github.com/plataformatec/devise/issues/2813
  devise_for :users, skip: [:registration, :confirmation, :password, :session, :unlock], controllers: { :omniauth_callbacks => 'users/omniauth_callbacks' }

  scope '(:locale)' do
    # We define here a route inside the locale thats just saves the current locale in the session
    get 'omniauth/:provider' => 'users/omniauth#localized', as: :localized_omniauth

    devise_for :users, skip: :omniauth_callbacks,
               :controllers => {:registrations => 'users/devise/registrations',
                                :clients_confirmations => 'users/devise/confirmations',
                                :passwords => 'users/devise/passwords',
                                :sessions => 'users/devise/sessions',
                                :unlocks => 'users/devise/unlocks' }

    # NOTE: put this AFTER the 'devise_for :users' line
    resources :users, only: [:index, :show, :edit, :update, :destroy]

    resources :artists do
      get :run #To run a specific crawler from artist
    end
    resources :crawlers, only: [:index, :create] #this is the crawler detector to create the artist or venue, depending on the url

    get 'privacy' => 'application#privacy'
    get 'terms' => 'application#terms'
    match '/contacts',     to: 'contacts#new', via: 'get' #for the contact form
    resources 'contacts', only: [:new, :create]

    resources :shows do
      patch 'set_visible', :constraints => {:format => /(js)/}
    end
    match 'filters_state' => 'shows#filters_state', :via => :get, :constraints => {:format => /(json)/}

    resources :show_votes, only: [:index, :create, :destroy]
    resources :subcategory_votes, only: [:create, :index]
    resources :categories, only: :index

    namespace :states, :path => '/states/:state_id' do
      get '/cities/:id', :controller => 'maps', :action => 'get_cities'
    end

    # You can have the root of your site routed with "root"
    root 'shows#index'

    post 'reload_shows', :controller => 'shows', :action => 'reload_shows'
    post 'reload_suggestion', :controller => 'shows', :action => 'reload_suggestion'

    #There is a bug in the scoped routes with forms: https://github.com/rails/rails/issues/12178
    resources :countries, only: [:index, :show] do
      get 'districts_select'
      resources :districts, only: [:index, :show] do
        resources :cities do
          resources :venues do
            get :run #To run a specific crawler from website
          end
        end
      end
    end
  end

end

app/models/artist.rb
class Artist < ActiveRecord::Base
  include CountriesHelper

  extend FriendlyId
  friendly_id :slug_candidates, use: :slugged

  belongs_to :user
  belongs_to :subcategory

  has_many :shows
  has_many :artist_crawler_reports

  validates_presence_of :user, :name, :website
  validates_presence_of :crawler_feed_url, :if => :enable_crawler
  validates_uniqueness_of :name, :message => I18n.t('activerecord.models.artist.errors.unique_artist')

  validates_inclusion_of :country_alpha2, in: Country.all.map{|c| c[1]}
  validate :valid_crawler, :if => :enable_crawler

  private
  def valid_crawler
    errors.add(:crawler_feed_url, I18n.t('activerecord.models.artist.errors.invalid_crawler')) unless IArtistCrawler::RECOGNIZED_CRAWLERS.include?(ICrawler.get_crawler_class(self.crawler_feed_url))
  end

  has_attached_file :photo,
                    :styles => { :medium => "200x200>", :thumb => "50x50>" },
                    :default_url => "/assets/artists/missing.jpg",
                    :url  => "/system/:class/:attachment/:id/:style/:basename.:extension",
                    :path => ":rails_root/public/system/:class/:attachment/:id/:style/:basename.:extension"
                    #:path => ":rails_root/public/assets/artists/:id/photo/:style/:basename.:extension"
  validates_attachment_size :photo, :less_than => 250.kilobytes
  validates_attachment_content_type :photo, :content_type => ['image/jpeg', 'image/png']
  validates_presence_of :photo, if: Proc.new{|f| f.external_photo.nil? or f.external_photo.blank? }

  validates_presence_of :subcategory

  has_attached_file :icon,
                    :default_url => "/assets/venues/missing.png",
                    :url  => "/system/:class/:attachment/:id/:style/:basename.:extension",
                    :path => ":rails_root/public/system/:class/:attachment/:id/:style/:basename.:extension"
                    #:path => ":rails_root/public/assets/venues/:id/icon/:style/:basename.:extension"
  validates_attachment_size :icon, :less_than => 3.kilobytes
  validates_attachment_content_type :icon, :content_type => ['image/jpeg', 'image/png']
  #validates_presence_of :icon, if: Proc.new{|f| f.external_icon.nil? or f.external_icon.blank? }

  validate :icon_dimensions
  private
  def icon_dimensions
    required_width  = 16
    required_height = 16
    #p icon.inspect
    if(icon.queued_for_write[:original])
      dimensions = Paperclip::Geometry.from_file(icon.queued_for_write[:original].path)
      errors.add(:icon, "#{I18n.t('activerecord.models.artist.errors.invalid_width')} #{required_width}px") unless dimensions.width == required_width
      errors.add(:icon, "#{I18n.t('activerecord.models.artist.errors.invalid_height')} #{required_height}px") unless dimensions.height == required_height
    end
  end

  public
  def photo_url
    if !self.external_photo.blank?
      self.external_photo
    else
      self.photo.url(:medium)
    end
  end

  def icon_url
    if !self.external_icon.blank?
      self.external_icon
    else
      self.icon.url
    end
  end

  after_update do #update the denormalized attributes in the shows list
    if(self.name_changed? or self.icon_file_name_changed? or self.external_icon_changed?)
      self.shows.update_all(name: name, artist_icon: icon_url)
    end
  end

  # Try building a slug based on the following fields in increasing order of specificity.
  def slug_candidates
    [
        :name,
        [:country_name, :name]
    ]
  end
  def country_name
    Country[self.country_alpha2].name if self.country_alpha2
  end

end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController

  load_and_authorize_resource :except => [:run] #This is necessary because it is not REST
  skip_load_resource :only => [:create] #This is necessary or it will fail

  # GET /artists
  # GET /artists.json
  def index
    @artists = Artist.all
  end

  # GET /artists/1
  # GET /artists/1.json
  def show
    require 'json'
    @latest_artist_crawler_reports = @artist.artist_crawler_reports.order(id: :desc)

    if ICrawler.get_crawler_class(@artist.crawler_feed_url) == ICrawler::FACEBOOK
      @graph = Koala::Facebook::API.new(Showgeeks::FACEBOOK_APPLICATION_TOKEN)
      p "FB ID: #{ICrawler.parse_user_id(@artist.crawler_feed_url)}"
      @fb_eventList = @graph.get_connections(ICrawler.parse_user_id(@artist.crawler_feed_url), 'events')
    elsif ICrawler.get_crawler_class(@artist.crawler_feed_url) == ICrawler::BANDS_IN_TOWN
      @bandsintown_eventList = Bandsintown::Artist.new({:name => ICrawler.parse_bands_in_town_id(@artist.crawler_feed_url)}).events
    end

    @showList = @artist.shows.where("DATE(date) >= ?", Time.zone.now.beginning_of_day).order(date: :asc)
  end

  # GET /artists/new
  def new
    @artist = Artist.new(
                       name: params[:name],
                       address: params[:address],
                       phone: params[:phone],
                       website: params[:website],
                       external_photo: params[:external_photo],
                       external_icon: params[:external_icon],
                       trusted: params[:trusted],
                       enable_crawler: params[:enable_crawler],
                       crawler_feed_url: params[:crawler_feed_url]
    #external_icon: 'http://www.theatrocirco.com/favIcon.ico',
    #external_photo: "https://fbcdn-profile-a.akamaihd.net/hprofile-ak-xaf1/t1.0-1/p200x200/306132_10150920499747486_425451963_n.jpg"
    )
  end

  # GET /artists/1/edit
  def edit
  end

  # POST /artists
  # POST /artists.json
  def create
    @artist = Artist.new(artist_params)
    @artist.user_id = current_user.id

    respond_to do |format|
      if @artist.save
        format.html { redirect_to @artist, notice: 'Artist was successfully created.' }
        format.json { render action: 'show', status: :created, location: @artist }
      else
        format.html { render action: 'new' }
        format.json { render json: @artist.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /artists/1
  # PATCH/PUT /artists/1.json
  def update
    respond_to do |format|
      if @artist.update(artist_params)
        format.html { redirect_to @artist, notice: 'Artist was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @artist.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /artists/1
  # DELETE /artists/1.json
  def destroy
    @artist.destroy
    respond_to do |format|
      format.html { redirect_to artists_url }
      format.json { head :no_content }
    end
  end

  # GET artists/1/run
  include CrawlersHelper
  def run
    @artist = Artist.find(params[:artist_id])
    authorize! :run_artist_crawler, @artist # Cancan custom function

    if(@artist and ICrawler.get_crawler_class(@artist.crawler_feed_url))
      #Run rake task
      case ICrawler.get_crawler_class(@artist.crawler_feed_url)
        when IVenueCrawler::FACEBOOK
          job = FacebookArtistEvents.new(@artist)
        when IVenueCrawler::BANDS_IN_TOWN
          job = BandsInTownArtistEvents.new(@artist)
        else
          logStr = "Unknown artist crawler name for venue: #{@artist.name}"
      end
      if job
        initial_time = Time.now
        job.crawl
        logStr = crawlerLogAsHtmlList(job.log)
        job.set_duration(Time.at(Time.now.to_i - initial_time.to_i).utc)
        ArtistCrawlerReport.create(artist_id: @artist.id, duration: job.duration, success_count: job.success, edit_count: job.edit, cancelled_count: job.cancelled, fail_count: job.fail, skip_count: job.skip, log: logStr, automatic: false)
        redirect_to artist_path(@artist), notice: "Crawler #{@artist.name} complete."
      end
    else
      redirect_to artists_path, notice: "No artist or crawler found"
    end
  end

  private
    # Never trust parameters from the scary internet, only allow the white list through.
    def artist_params
      params.require(:artist).permit(:user_id, :visible, :subcategory_id, :name, :address, :country_alpha2, :phone, :website, :external_icon, :icon, :external_photo, :photo, :trusted, :enable_crawler, :crawler_feed_url)
    end
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/views/artists/_form.html.erb
<%= simple_form_for(@artist, :html => { :multipart => true }) do |f| %>
  <%= f.error_notification %>
    <div class="container-fluid">
      <div class="row-fluid col-md-10">
        <div class="col-md-3 text-center">
          <div class="control-group">
            <strong><%= I18n.t('simple_form.labels.artist.photo') %></strong><br/>
            <% if @artist.external_photo %>
                <%= image_tag @artist.external_photo, width: '200' %> <br/>
                <%= link_to 'link', @artist.external_photo %>
            <% else %>
                <%= image_tag @artist.photo.url, width: '200' %>
            <% end %>
          </div>
          <div class="control-group">
            <strong><%= I18n.t('simple_form.labels.artist.icon') %></strong><br/>
            <% if @artist.external_icon %>
                <%= image_tag @artist.external_icon, size: '16x16' %><br/>
                <%= link_to 'external link', @artist.external_icon %>
            <% else %>
                <%= image_tag @artist.icon.url, size: '16x16' %>
            <% end %>
          </div>
        </div>
        <div class="col-md-9">

          <%= f.input :external_photo %>
          <%= f.input :photo do %>
              <%= f.file_field :photo %>
          <% end %>

          <%= f.input :external_icon %>
          <%= f.input :icon do %>
              <%= f.file_field :icon %>
          <% end %>

          <div class="checkbox">
              <%= f.input_field :visible, :inline_label => true %>
          </div>

          <%= f.input :name %>
          <%= f.input :address %>
          <%= f.input :country_alpha2 do %>
              <%= f.select :country_alpha2, options_for_select(available_countries.map {|c| [c.name, c.alpha2]}.insert(0, ''), @artist.country_alpha2), {}, { id:'cb_generic_country', class:'form-control' } %>
          <% end %>


          <%= f.input :phone %>

          <%= f.input :website %>
          <%= f.association :subcategory %>
          <div class="checkbox">
            <%= f.input_field :trusted, :inline_label => true %>
          </div>

          <hr/>
          <div class="checkbox">
            <%= f.input_field :enable_crawler, :inline_label => true %>
          </div>
          <%= f.input :crawler_feed_url %>

          <br/>
          <div class="form-actions">
            <%= f.button :submit %>
          </div>
        </div>
      </div>
    </div>

<% end %>

app/views/artists/edit.html.erb
<h2><%= "#{I18n.t('helpers.links.edit')} #{I18n.t('activerecord.models.artist.one')}" %> </h2>

<%= render 'form' %>

<%= link_to I18n.t('helpers.links.show'), @artist %> |
<%= link_to I18n.t('helpers.links.back'), artists_path %>

app/views/artists/index.html.erb
<h1><%= I18n.t('activerecord.models.artist.other') %></h1>

<table class='table table-condensed table-striped'>
  <thead>
  <tr>
    <th></th>
    <th><%= I18n.t('simple_form.labels.artist.name') %></th>
    <th><%= I18n.t('simple_form.labels.artist.country_alpha2') %></th>
    <th><%= I18n.t('simple_form.labels.artist.subcategory') %></th>
    <% if current_user and current_user.admin? %>
      <th>Crawler</th>
    <% end %>
  </tr>
  </thead>

  <tbody>
  <% @artists.each do |artist| %>
      <tr>
        <td style="width: 20px">
          <%= image_tag artist.icon_url, size: '16x16' %>
        </td>
        <td>
          <i class="<%= artist.trusted ? 'glyphicon glyphicon-eye-open' : 'glyphicon glyphicon-eye-close' %>" title="<%= artist.trusted ? I18n.t('artists.artist.trusted_crawler_info') : I18n.t('artists.artist.untrusted_crawler_info') %>"></i>
          <i class="<%= artist.enable_crawler ? 'glyphicon glyphicon-ok' : 'glyphicon glyphicon-remove' %>" title="<%= artist.enable_crawler ? I18n.t('artists.artist.enabled_crawler_info') : I18n.t('artists.artist.disabled_crawler_info') %>"></i>
          <%= link_to artist.name, artist_path(artist) %>
        </td>
        <td>
          <%= artist.country_alpha2 %>
        </td>
        <td>
          <%= artist.subcategory.name %>
        </td>
        <% if current_user and current_user.admin? %>
            <td><%= ICrawler.get_crawler_class_icon(artist.crawler_feed_url) %></td>
        <% end %>

      </tr>
  <% end %>
  </tbody>
</table>

<br>


<%= link_to "#{I18n.t('helpers.links.new')} #{I18n.t('activerecord.models.artist.one')}", new_artist_path %>

app/views/artists/new.html.erb
<h1><%= "#{I18n.t('helpers.links.new')} #{I18n.t('activerecord.models.artist.one')}" %></h1>

<%= render 'form' %>

<%= link_to I18n.t('helpers.links.back'), artists_path %>

app/views/artists/show.html.erb
<p id="notice"><%= notice %></p>

<div class="row-fluid">
  <div class="col-md-4">
    <div class="text-center">
        <h3><%= @artist.name %> </h3>
        <p><%= @artist.subcategory.name %></p>
        <%= image_tag @artist.photo_url, width: '200' %>
        <p><%= link_to(@artist.website, @artist.website, :target => 'blank') unless @artist.website.blank? %></p>
      <div class="panel-group" id="accordion">
        <a data-toggle="collapse" data-parent="#accordion" href="#collapseOne"> <%= I18n.t('artists.artist.plus_info') %> </a>
        <div id="collapseOne" class="panel-collapse collapse">
          <div class="panel-body text-left">
            <p>
              <span class='glyphicon glyphicon-home'></span>
              <%= @artist.address if !@artist.address.blank? %>
              <br/>
              <%= Country[@artist.country_alpha2].try(:name) %>
            </p>
            <% if !@artist.phone.blank? %>
                <p>
                  <span class='glyphicon glyphicon-earphone'></span>
                  <%= @artist.phone %>
                </p>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="col-md-8">
    <h4> <%= I18n.t('artists.artist.shows_of', venue: @artist.name) %>:</h4>
    <dl>
      <% @showList.each_with_index do |item, index| %>
          <% if index == 0 || @showList[index-1].date.to_date != @showList[index].date.to_date %>
              <br/>
              <dt>
                <% if Date.today == item.date.to_date %>
                    <%= I18n.t('date.today')%>
                <% elsif Date.tomorrow == item.date.to_date %>
                    <%= I18n.t('date.tomorrow')%>
                <% else %>
                    <%= I18n.l item.date %>
                <% end %>
              </dt>
          <% end %>
          <dd>
            <%= link_to item.city_name.html_safe, show_path(item.id) %>
            <%= "- #{Country[item.country_alpha2].states[item.district_alpha2]['name']}" if show_state(item.country_alpha2) %>
            <%= "- #{I18n.t('shows.canceled')}"  if item.canceled %>
          </dd>
      <% end %>
    </dl>
  </div>

  <div class="row-fluid col-md-11 col-md-offset-1">
    <% if current_user and current_user.admin? %>
        <hr/>
        <h4>Admin info</h4>
        <p>
          <strong>Icon:</strong>
          <%= image_tag @artist.icon_url, size: '16x16' %>
        </p>
        <p>
          <strong>Visible:</strong>
          <% if @artist.visible %>
              Yes
          <% else %>
              <span class="glyphicon glyphicon-warning-sign">No</span>
          <% end %>
        </p>
        <p>
          <strong>Trusted:</strong>
          <% if @artist.trusted %>
              Yes
          <% else %>
              <span class="label label-warning">No</span>
          <% end %>
        </p>
        <p>
          <strong>Enable crawler:</strong>
          <% if @artist.enable_crawler %>
              Yes
          <% else %>
              <span class="label label-important">No</span>
          <% end %>
        </p>
        <p>
          <strong>Crawler feed URL:</strong>
          <%= link_to @artist.crawler_feed_url, @artist.crawler_feed_url %>
        </p>
        <p>
          <strong>Detected Crawler Class:</strong>
          <text class='label label-info'><%= ICrawler.get_crawler_class(@artist.crawler_feed_url) %></text>
          <% if ICrawler.get_crawler_class(@artist.crawler_feed_url) %>
              <%= link_to 'run crawler!', artist_run_path(@artist), class: 'btn btn-small' %>
          <% end %>
        </p>
        <% if ICrawler.get_crawler_class(@artist.crawler_feed_url) == IVenueCrawler::FACEBOOK %>
            <p>
              <strong>Facebook User Id:</strong>
              <%= ICrawler.parse_user_id(@artist.crawler_feed_url) %>
            </p>
        <% end %>
        <% if @fb_eventList %>
            <div class="accordion" id="fb_events_accordion">
              <div class="accordion-group">
                <div class="accordion-heading">
                  <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href="#collapseCrawlerSource">
                    <strong>Facebook events</strong>
                  </a>
                </div>
                <div id="collapseCrawlerSource" class="panel-collapse collapse">
                  <div class="accordion-inner">
                    <% @fb_eventList.each do |fb_event| %>
                        <li>
                          <% if DateTime.parse(fb_event['start_time']) < DateTime.now %>
                              <%= "[OLD]" %>
                          <% end %>
                          <%="#{fb_event['name']} @ #{DateTime.parse(fb_event['start_time'])}" %>
                          <br/>
                        </li>
                    <% end %>
                  </div>
                </div>
              </div>
            </div>
        <% elsif @bandsintown_eventList %>
            <div class="accordion" id="fb_events_accordion">
              <div class="accordion-group">
                <div class="accordion-heading">
                  <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href="#collapseCrawlerSource">
                    <strong>Bands In Town events</strong>
                  </a>
                </div>
                <div id="collapseCrawlerSource" class="panel-collapse collapse">
                  <div class="accordion-inner">
                    <% @bandsintown_eventList.each do |bit_event| %>
                        <li>
                          <% if bit_event.datetime < DateTime.now %>
                              <%= "[OLD]" %>
                          <% end %>
                          <%="[#{bit_event.datetime}]: #{bit_event.venue.country} - #{bit_event.venue.city} @ #{bit_event.venue.name}" %>
                          <br/>
                        </li>
                    <% end %>
                  </div>
                </div>
              </div>
            </div>
        <% end %>
          <div class="panel-group " id="accordion">
            <% @latest_artist_crawler_reports.each do |crawler_report| %>
                <div class="panel panel-default">
                  <div class="panel-heading">
                    <h4 class="panel-title">
                      <a data-toggle="collapse" data-parent="#accordion" href="#collapse<%= crawler_report.id %>">
                        <% if crawler_report.automatic %>
                            <i class='glyphicon glyphicon-hdd' title="made by automatic task"></i>
                        <% end %>
                        <%= crawler_report.created_at %>
                        [
                        duration:<%= crawler_report.duration.utc.strftime("%H:%M:%S") %> |
                        success:<%= crawler_report.success_count %> |
                        edit:<%= crawler_report.edit_count %> |
                        cancelled:<%= crawler_report.cancelled_count %> |
                        fail:<%= crawler_report.fail_count %> |
                        skip:<%= crawler_report.skip_count %>
                        ]
                      </a>
                    </h4>
                  </div>
                  <div id="collapse<%= crawler_report.id %>" class="panel-collapse collapse">
                    <div class="panel-body">
                      <strong>Log:</strong>
                      <pre>
                        <%= crawler_report.log.html_safe %>
                      </pre>
                    </div>
                  </div>
                </div>
            <% end %>
          </div>
        <hr/>
  <% end %>
  </div>
 </div>
</div>
<br/>
<div class="col-md-offset-1">
    <% if can? :edit, @artist %>
        <%= link_to I18n.t('helpers.links.edit'), edit_artist_path(@artist) %> |
    <% end %>
    <%= link_to I18n.t('activerecord.models.artist.other'), artists_path %>

    <% if can? :destroy, @artist %>
        <hr class="divider"></hr>
        <div class="alert alert-error">
          <%= link_to I18n.t('helpers.links.destroy'), artist_path(@artist), method: :delete, data: { confirm: I18n.t('helpers.links.confirm') } %>
          <%= I18n.t('helpers.titles.delete_warning', model: I18n.t('activerecord.models.artist.one')) %>
        </div>
    <% end %>
</div>