config/routes.rb
Showgeeks::Application.routes.draw do

  # We need to define devise_for just omniauth_callbacks otherwise it does not work with scoped locales
  # see https://github.com/plataformatec/devise/issues/2813
  devise_for :users, skip: [:registration, :confirmation, :password, :session, :unlock], controllers: { :omniauth_callbacks => 'users/omniauth_callbacks' }

  scope '(:locale)' do
    # We define here a route inside the locale thats just saves the current locale in the session
    get 'omniauth/:provider' => 'users/omniauth#localized', as: :localized_omniauth

    devise_for :users, skip: :omniauth_callbacks,
               :controllers => {:registrations => 'users/devise/registrations',
                                :clients_confirmations => 'users/devise/confirmations',
                                :passwords => 'users/devise/passwords',
                                :sessions => 'users/devise/sessions',
                                :unlocks => 'users/devise/unlocks' }

    # NOTE: put this AFTER the 'devise_for :users' line
    resources :users, only: [:index, :show, :edit, :update, :destroy]

    resources :artists do
      get :run #To run a specific crawler from artist
    end
    resources :crawlers, only: [:index, :create] #this is the crawler detector to create the artist or venue, depending on the url

    get 'privacy' => 'application#privacy'
    get 'terms' => 'application#terms'
    match '/contacts',     to: 'contacts#new', via: 'get' #for the contact form
    resources 'contacts', only: [:new, :create]

    resources :shows do
      patch 'set_visible', :constraints => {:format => /(js)/}
    end
    match 'filters_state' => 'shows#filters_state', :via => :get, :constraints => {:format => /(json)/}

    resources :show_votes, only: [:index, :create, :destroy]
    resources :subcategory_votes, only: [:create, :index]
    resources :categories, only: :index

    namespace :states, :path => '/states/:state_id' do
      get '/cities/:id', :controller => 'maps', :action => 'get_cities'
    end

    # You can have the root of your site routed with "root"
    root 'shows#index'

    post 'reload_shows', :controller => 'shows', :action => 'reload_shows'
    post 'reload_suggestion', :controller => 'shows', :action => 'reload_suggestion'

    #There is a bug in the scoped routes with forms: https://github.com/rails/rails/issues/12178
    resources :countries, only: [:index, :show] do
      get 'districts_select'
      resources :districts, only: [:index, :show] do
        resources :cities do
          resources :venues do
            get :run #To run a specific crawler from website
          end
        end
      end
    end
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable,
  # :lockable, :timeoutable and :omniauthable
  devise :omniauthable, :omniauth_providers => [:facebook]
  def self.from_omniauth(auth)
    where(auth.slice(:provider, :uid)).first_or_create do |user|
      Rails.logger.info "Auth variable inspect: #{auth.inspect}"
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      user.name = auth.info.name   # assuming the user model has a name
      user.avatar = process_uri(auth.info.image) # assuming the user model has an image
      user.skip_confirmation! #For facebook authentication, no need for confirmation
    end
  end

  private
  def self.process_uri(uri)
    avatar_url = URI.parse(uri)
    avatar_url.scheme = 'https'
    avatar_url.to_s
  end

  public
  has_many :shows
  has_many :subcategory_votes
  has_many :show_votes
  has_many :venues

  belongs_to :seller, :class_name => 'User', :foreign_key => 'seller_id'
  has_many :clients, :class_name => 'User', :foreign_key => 'seller_id'

  attr_accessor :affiliate_email
  # If there is a affiliate, it must be a valid seller
  validate :affiliate_validation
  private
  def affiliate_validation
    if !self.try(:affiliate_email).blank?  #in a omniauth login affiliate_email is non-existent
      affiliate_user = User.find_by(email: self.affiliate_email)#.try(:seller)
      if affiliate_user.nil?
        self.errors.add(:affiliate_email, "#{I18n.t('activerecord.models.user.errors.invalid_user')} (0)")
        return
      elsif !affiliate_user.is_seller
        self.errors.add(:affiliate_email, "#{I18n.t('activerecord.models.user.errors.invalid_user')} (1)")
        return
      end
    end
  end

  before_save do
    if self.try(:affiliate_email) #in a omniauth login affiliate_email is non-existent
      self.seller_id = User.find_by(email: self.affiliate_email).try(:id)
    end
  end

  has_attached_file :avatar,
                    :styles => { :medium => "300x300>", :thumb => "30x30>" },
                    :default_url => "/assets/users/avatar/:style/missing.png",
                    :url  => "/system/:class/:attachment/:id/:style/:basename.:extension",
                    :path => ":rails_root/public/system/:class/:attachment/:id/:style/:basename.:extension"
                    #:path => ":rails_root/public/assets/users/:id/:style/:basename.:extension"

  validates_attachment_size :avatar, :less_than => 50.kilobytes
  validates_attachment_content_type :avatar, :content_type => ['image/jpeg', 'image/png']

  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable

  validates_uniqueness_of :email
  validates_presence_of :name
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController

  def facebook
    handle_redirect('devise.facebook_data', 'Facebook')
  end

  private
  def handle_redirect(_session_variable, kind)
    # here we force the locale to the session locale so it siwtches to the correct locale
    I18n.locale = session[:omniauth_login_locale] || I18n.default_locale
    user = User.from_omniauth(request.env["omniauth.auth"])
    if user.persisted?
      sign_in_and_redirect user, event: :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => kind) if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

=begin
  #def twitter
  #  handle_redirect('devise.twitter_uid', 'Twitter')
  #end
  def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end
=end
end

app/controllers/users/omniauth_controller.rb
class OmniauthController < ApplicationController

  def localized
    # Just save the current locale in the session and redirect to the unscoped path as before
    session[:omniauth_login_locale] = I18n.locale
    redirect_to user_omniauth_authorize_path(params[:provider])
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  load_and_authorize_resource

  # GET /users
  def index
    if current_user.admin
      @users = User.all
    else
      @users = current_user.clients
    end
  end

  # GET /users/1
  def show
    #p @user.inspect
  end

  # GET /users/1/edit
  def edit
  end

  # PATCH/PUT /users/1
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to user_path(@user), notice: 'User was successfully updated.' }
      else
        format.html { render action: 'edit' }
      end
    end
  end

  # DELETE /cities/1
  # DELETE /cities/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_path() }
    end
  end

  private
  # Never trust parameters from the scary internet, only allow the white list through.
  def user_params
    if can? :edit_user_class, User
      params.require(:user).permit(:name, :is_seller, :affiliate_email, :country_alpha2, :district_alpha2, :city_id, :avatar)
    else
      params.require(:user).permit(:name, :country_alpha2, :district_alpha2, :city_id, :avatar)
    end
  end

end

app/helpers/users_helper.rb
module UsersHelper

  def user_type_icon(user)
    if user.admin
      "<i class='glyphicon glyphicon-tower'></i>"
    elsif user.is_seller
      "<i class='glyphicon glyphicon-briefcase'></i>"
    else
      "<i class='glyphicon glyphicon-user'></i>"
    end
  end

end

app/views/users/edit.html.erb
<h3><%= "#{I18n.t('helpers.links.edit')}: #{@user.name}" %> </h3>

<%= simple_form_for(@user, html: { :class => 'form-horizontal'}) do |f| %>
    <%= f.error_notification %>

    <div class="container-fluid">
      <div class="row-fluid col-md-12">
          <div class="col-md-2">
            <div class="text-center">
              <p class="help-block"><%= I18n.t('simple_form.labels.user.profile_picture') %> </p>
              <%= image_tag @user.avatar.url %>
              <%= f.file_field :avatar %>
            </div>
          </div>
          <div class="col-md-offset-1 col-md-4">
            <div class="form-inputs form-horizontal">
              <%= f.input :name %>

              <br/>
              <div class="control-group">
                <div class="controls help-block">
                  <h4 class="help-block"><%= I18n.t('users.user.add_your_location_suggestion') %>. </h4>
                </div>
              </div>

              <%= f.input :country_alpha2 do %>
                  <%= f.select :country_alpha2, options_for_select(available_countries.map {|c| [c.name, c.alpha2]}.insert(0, ''), @user.country_alpha2), {}, {id:'cb_generic_country', :class => 'form-control', :include_blank => 'None Specified' } %>
              <% end %>
              <%= f.input :district_alpha2 do %>
                  <%= f.select :district_alpha2, options_for_select((Country[@user.country_alpha2]? (Country[@user.country_alpha2].states.map {|c| [c[1]['name'], c[0]]}):{}), @user.district_alpha2), {}, { id:'cb_generic_district', class:'form-control', include_blank: true } %>
              <% end %>
              <%= f.input :city_id do %>
                  <%= f.select :city_id, options_for_select(City.from_country(@user.country_alpha2).from_district(@user.district_alpha2).map { |c| [c.name, c.id]}, @user.city_id), {}, { :id => 'cb_generic_city', class:'form-control', include_blank: true } %>
              <% end %>
              <br/>
              <h3><%= I18n.t('users.user.edit_login_details_header') %></h3>
              <p> <%= link_to I18n.t('users.user.change_email_or_password'), edit_user_registration_path %></p>

              <% if can? :edit_user_class, User %>
                  <hr/>
                  <div class="form-inputs">
                    <div class="checkbox">
                      <%= f.input_field :is_seller, :inline_label => true %>
                    </div>
                    <%= f.input :affiliate_email %>
                  </div>
              <% end %>

            </div>
            <br/>
            <div class="form-actions">
              <%= f.button :submit %>
            </div>
          </div>
      </div>
    </div>
    <br/>
<% end %>

<%= link_to I18n.t('helpers.links.show'), user_path(@user) %> |
<%= link_to I18n.t('helpers.links.back'), user_path(@user) %>

app/views/users/index.html.erb
<h3> <%= I18n.t('activerecord.models.user.other') %>: <%= @users.size %></h3>

<table class='table table-condensed table-striped'>
  <thead>
  <tr>
    <th><%= I18n.t('users.user.user_type') %></th>
    <th><%= I18n.t('simple_form.labels.user.name') %></th>
    <th><%= I18n.t('simple_form.labels.user.is_seller') %></th>
    <th><%= I18n.t('simple_form.labels.user.country_alpha2') %></th>
    <th><%= I18n.t('simple_form.labels.user.district_alpha2') %></th>
  </tr>
  </thead>

  <tbody>
  <% @users.each do |user| %>
      <tr>
        <td style="width: 50px;"><%= user_type_icon(user).html_safe %></td>
        <td><%= link_to_if (can? :show, User), user.name, user_path(user)  %></td>
        <td><%= user.seller.try(:name)  %></td>
        <td><%= user.country_alpha2  %></td>
        <td><%= Country[user.country_alpha2].states[user.district_alpha2]['name'] if !user.country_alpha2.blank?  %></td>
      </tr>
  <% end %>
  </tbody>
</table>

<br>

app/views/users/show.html.erb
<h1><%= @user.name %></h1>

<p id="notice"><%= notice %></p>

<p>
  <strong><%= I18n.t('users.user.user_type') %>:</strong>
  <%= I18n.t('users.user.admin_type') if @user.admin %>
  <%= I18n.t('users.user.seller_type') if @user.is_seller %>
  <%= I18n.t('users.user.normal_type') unless @user.admin or @user.is_seller %>
  <%= user_type_icon(@user).html_safe %>
</p>

<p>
  <strong><%= I18n.t('simple_form.labels.user.country_alpha2') %>:</strong>
  <%= Country[@user.country_alpha2].try(:name) %>
</p>

<p>
  <strong><%= I18n.t('simple_form.labels.user.district_alpha2') %>:</strong>
  <%= Country[@user.country_alpha2].states[@user.district_alpha2]['name'] if !@user.country_alpha2.blank? %>
</p>

<p>
  <strong><%= I18n.t('simple_form.labels.user.city_id') %>:</strong>
  <%= City.find(@user.city_id).name if @user.city_id %>
</p>

<p>
  <strong><%= I18n.t('users.user.affiliate_user') %>:</strong>
  <%= @user.seller.try(:name) %>
</p>
<hr/>
<% if can? :edit, @user %>
    <%= link_to I18n.t('helpers.links.edit'), edit_user_path(@user) %> |
<% end %>
<%= link_to I18n.t('helpers.links.back'), user_path(@user) %>

<% if can? :delete, @user %>
    <hr class="divider"></hr>
    <div class="alert alert-error">
      <%= link_to I18n.t('helpers.links.destroy'), user_path(@user), method: :delete, data: { confirm: I18n.t('helpers.links.confirm') } %>
      <%= I18n.t('helpers.titles.delete_warning', model: I18n.t('activerecord.models.user.one')) %>
    </div>
<% end %>