config/routes.rb
Showgeeks::Application.routes.draw do

  # We need to define devise_for just omniauth_callbacks otherwise it does not work with scoped locales
  # see https://github.com/plataformatec/devise/issues/2813
  devise_for :users, skip: [:registration, :confirmation, :password, :session, :unlock], controllers: { :omniauth_callbacks => 'users/omniauth_callbacks' }

  scope '(:locale)' do
    # We define here a route inside the locale thats just saves the current locale in the session
    get 'omniauth/:provider' => 'users/omniauth#localized', as: :localized_omniauth

    devise_for :users, skip: :omniauth_callbacks,
               :controllers => {:registrations => 'users/devise/registrations',
                                :clients_confirmations => 'users/devise/confirmations',
                                :passwords => 'users/devise/passwords',
                                :sessions => 'users/devise/sessions',
                                :unlocks => 'users/devise/unlocks' }

    # NOTE: put this AFTER the 'devise_for :users' line
    resources :users, only: [:index, :show, :edit, :update, :destroy]

    resources :artists do
      get :run #To run a specific crawler from artist
    end
    resources :crawlers, only: [:index, :create] #this is the crawler detector to create the artist or venue, depending on the url

    get 'privacy' => 'application#privacy'
    get 'terms' => 'application#terms'
    match '/contacts',     to: 'contacts#new', via: 'get' #for the contact form
    resources 'contacts', only: [:new, :create]

    resources :shows do
      patch 'set_visible', :constraints => {:format => /(js)/}
    end
    match 'filters_state' => 'shows#filters_state', :via => :get, :constraints => {:format => /(json)/}

    resources :show_votes, only: [:index, :create, :destroy]
    resources :subcategory_votes, only: [:create, :index]
    resources :categories, only: :index

    namespace :states, :path => '/states/:state_id' do
      get '/cities/:id', :controller => 'maps', :action => 'get_cities'
    end

    # You can have the root of your site routed with "root"
    root 'shows#index'

    post 'reload_shows', :controller => 'shows', :action => 'reload_shows'
    post 'reload_suggestion', :controller => 'shows', :action => 'reload_suggestion'

    #There is a bug in the scoped routes with forms: https://github.com/rails/rails/issues/12178
    resources :countries, only: [:index, :show] do
      get 'districts_select'
      resources :districts, only: [:index, :show] do
        resources :cities do
          resources :venues do
            get :run #To run a specific crawler from website
          end
        end
      end
    end
  end

end

app/models/show_vote.rb
class ShowVote < ActiveRecord::Base
  belongs_to :user
  belongs_to :show

  VOTE_TYPES = [
      TYPE_ATTENDING = 1,
      TYPE_COMPLAINT_WRONG_INFO = 2,
      TYPE_COMPLAINT_SPAM = 3,
      TYPE_COMPLAINT_ABUSE = 4
  ]

  COMPLAINT_SHOW_THRESHOLD = 2 # Minimum amount of votes to show warnings to users

  BLUE_EVENT_ATTENDANCE_LEVEL = 10 # This is the level of attendance to turn the main list badge blue
  GREEN_EVENT_ATTENDANCE_LEVEL = 20 # This is the level of attendance to turn the main list badge green

  scope :attending, -> { where(vote_type: TYPE_ATTENDING) }
  scope :this_show, ->(show_id) { where(show_id: show_id) }

  scope :complaining_wrong_info, -> { where(vote_type: TYPE_COMPLAINT_WRONG_INFO) }
  scope :complaining_spam, -> { where(vote_type: TYPE_COMPLAINT_SPAM) }
  scope :complaining_abuse, -> { where(vote_type: TYPE_COMPLAINT_ABUSE) }

  #Unique pair: user and show
  validates_presence_of :user_id, :show_id, :vote_type
  validates_uniqueness_of :user_id, :scope => [:show_id, :vote_type]
  validates_inclusion_of :vote_type, :in => VOTE_TYPES, :if => :vote_type
end

app/controllers/show_votes_controller.rb
class ShowVotesController < ApplicationController
  load_and_authorize_resource

  # GET /show_votes
  # GET /show_votes.json
  def index
    @show_votes = ShowVote.all
  end

  # POST /show_votes
  # POST /show_votes.json
  def create
    success = false
    if(params[:show_vote])
      @show_vote = ShowVote.new(show_vote_params)
      success = @show_vote.save
    else
      @show_vote = ShowVote.find_by(user_id: current_user.id, show_id: params[:show_id], vote_type: params[:vote_type])
      if !@show_vote
        @show_vote = ShowVote.new(user_id: current_user.id, show_id: params[:show_id], vote_type: params[:vote_type], amount: 1)
        success = @show_vote.save
      end
    end

    #Find show
    if success
      @show = @show_vote.show
      if(@show)
        peopleAttendingCount = @show.show_votes.attending.count
        if (@show.attending != peopleAttendingCount)
          @show.update_attributes(attending: peopleAttendingCount)
        end
      end
    end

    #Reply as js
    respond_to do |format|
      if success
        format.html { redirect_to show_votes_path, notice: 'Operation successful.' }
        format.js { }
        format.json { head :no_content }
      else
        format.html { render action: 'new' }
        format.js
        format.json { render json: @show_vote.errors, status: :unprocessable_entity }
      end
    end

  end

  # DELETE /show_votes/1
  # DELETE /show_votes/1.json
  def destroy
    success = false
    @show_vote = current_user.show_votes.find(params[:id])
    if @show_vote
      success = @show_vote.destroy
    end
    if success
      #Find show
      @show = @show_vote.show
      if(@show)
        peopleAttendingCount = @show.show_votes.attending.count
        if (@show.attending != peopleAttendingCount)
          @show.update_attributes(attending: peopleAttendingCount)
        end
      end
    end
    respond_to do |format|
      format.html { redirect_to show_votes_url }
      format.js
      format.json { head :no_content }
    end
  end

  private
    # Never trust parameters from the scary internet, only allow the white list through.
    def show_vote_params
      params.require(:show_vote).permit(:user_id, :show_id, :vote_type, :amount, :info)
    end
end

app/helpers/show_votes_helper.rb
module ShowVotesHelper

  def markedAsWrongInfo?
    return current_user.show_votes.complaining_wrong_info.this_show(@show.id).count > 0
  end
  def markedAsSpam?
    return current_user.show_votes.complaining_spam.this_show(@show.id).count > 0
  end
  def markedAsAbusive?
    return current_user.show_votes.complaining_abuse.this_show(@show.id).count > 0
  end

end

app/views/show_votes/create.js.erb
<% case @show_vote.vote_type %>
<% when ShowVote::TYPE_ATTENDING %>
    $('#participants_votes').html("<%=j render partial: 'shows/votes/attending_votes', locals: {show: @show} %>");
    $('#div_participants_info_label').html("<%=j render partial: 'shows/votes/attending_info', locals: {show: @show} %>");
<% else %>
    $('#div_complaints').html("<%=j render partial: 'shows/votes/warning_votes', locals: {show: @show} %>");
    $('#div_denounceButton').html("<%=j render partial: 'shows/votes/denounce_button', locals: {show: @show} %>");
<% end %>

app/views/show_votes/destroy.js.erb
<% case @show_vote.vote_type %>
<% when ShowVote::TYPE_ATTENDING %>
    $('#participants_votes').html("<%=j render partial: 'shows/votes/attending_votes', locals: {show: @show} %>");
    $('#div_participants_info_label').html("<%=j render partial: 'shows/votes/attending_info', locals: {show: @show} %>");
<% else %>
    $('#div_complaints').html("<%=j render partial: 'shows/votes/warning_votes', locals: {show: @show} %>");
    $('#div_denounceButton').html("<%=j render partial: 'shows/votes/denounce_button', locals: {show: @show} %>");
<% end %>

app/views/show_votes/index.html.erb
<h1>Listing show_votes</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Show</th>
      <th>Type</th>
      <th>Amount</th>
      <th>Info</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @show_votes.each do |show_vote| %>
      <tr>
        <td><%= show_vote.user_id %></td>
        <td><%= show_vote.show_id %></td>
        <td><%= show_vote.vote_type %></td>
        <td><%= show_vote.amount %></td>
        <td><%= show_vote.info %></td>
        <td><%= link_to 'Show', show_vote %></td>
        <td><%= link_to 'Edit', edit_show_vote_path(show_vote) %></td>
        <td><%= link_to 'Destroy', show_vote, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Show vote', new_show_vote_path %>

app/views/show_votes/new.html.erb
<h1>New show_vote</h1>

<%= render 'form' %>

<%= link_to 'Back', show_votes_path %>