config/routes.rb
Showgeeks::Application.routes.draw do

  # We need to define devise_for just omniauth_callbacks otherwise it does not work with scoped locales
  # see https://github.com/plataformatec/devise/issues/2813
  devise_for :users, skip: [:registration, :confirmation, :password, :session, :unlock], controllers: { :omniauth_callbacks => 'users/omniauth_callbacks' }

  scope '(:locale)' do
    # We define here a route inside the locale thats just saves the current locale in the session
    get 'omniauth/:provider' => 'users/omniauth#localized', as: :localized_omniauth

    devise_for :users, skip: :omniauth_callbacks,
               :controllers => {:registrations => 'users/devise/registrations',
                                :clients_confirmations => 'users/devise/confirmations',
                                :passwords => 'users/devise/passwords',
                                :sessions => 'users/devise/sessions',
                                :unlocks => 'users/devise/unlocks' }

    # NOTE: put this AFTER the 'devise_for :users' line
    resources :users, only: [:index, :show, :edit, :update, :destroy]

    resources :artists do
      get :run #To run a specific crawler from artist
    end
    resources :crawlers, only: [:index, :create] #this is the crawler detector to create the artist or venue, depending on the url

    get 'privacy' => 'application#privacy'
    get 'terms' => 'application#terms'
    match '/contacts',     to: 'contacts#new', via: 'get' #for the contact form
    resources 'contacts', only: [:new, :create]

    resources :shows do
      patch 'set_visible', :constraints => {:format => /(js)/}
    end
    match 'filters_state' => 'shows#filters_state', :via => :get, :constraints => {:format => /(json)/}

    resources :show_votes, only: [:index, :create, :destroy]
    resources :subcategory_votes, only: [:create, :index]
    resources :categories, only: :index

    namespace :states, :path => '/states/:state_id' do
      get '/cities/:id', :controller => 'maps', :action => 'get_cities'
    end

    # You can have the root of your site routed with "root"
    root 'shows#index'

    post 'reload_shows', :controller => 'shows', :action => 'reload_shows'
    post 'reload_suggestion', :controller => 'shows', :action => 'reload_suggestion'

    #There is a bug in the scoped routes with forms: https://github.com/rails/rails/issues/12178
    resources :countries, only: [:index, :show] do
      get 'districts_select'
      resources :districts, only: [:index, :show] do
        resources :cities do
          resources :venues do
            get :run #To run a specific crawler from website
          end
        end
      end
    end
  end

end

app/models/show.rb
class Show < ActiveRecord::Base
  extend FriendlyId
  friendly_id :slug_candidates, use: :slugged

  belongs_to :user
  belongs_to :category
  belongs_to :subcategory
  belongs_to :city

  belongs_to :venue
  belongs_to :artist

  has_many :subcategory_votes
  has_many :show_votes

  NOT_TRUSTED_SOURCE_LEVEL = 1
  TRUSTED_SOURCE_LEVEL = 101

  VISIBLE_YES = 1
  VISIBLE_NO = 0
  VISIBLE_DONT_KNOW = -1
  VISIBLE_IGNORE = -2
  VISIBLE_OPTIONS = [VISIBLE_YES, VISIBLE_NO, VISIBLE_DONT_KNOW, VISIBLE_IGNORE]

  has_attached_file :photo,
                    :styles => { :medium => "200x200>", :thumb => "50x50>" },
                    :default_url => "/assets/shows/missing.png",
                    :url  => "/system/:class/:attachment/:id/:style/:basename.:extension",
                    :path => ":rails_root/public/system/:class/:attachment/:id/:style/:basename.:extension"
                    #:path => ":rails_root/public/assets/shows/:id/photo/:style/:basename.:extension"
  #validates_attachment_presence :avatar
  validates_attachment_size :photo, :less_than => 500.kilobytes
  validates_attachment_content_type :photo, :content_type => ['image/jpeg', 'image/png']

  scope :from_country, lambda {|country_alpha2| where(country_alpha2: country_alpha2)}
  scope :from_district, lambda {|district_alpha2| where(district_alpha2: district_alpha2)}

  validates_uniqueness_of :name, :scope => [:venue_name, :date, :country_alpha2, :district_alpha2, :city_id]
  validates_presence_of :user_id, :name, :date, :country_alpha2, :district_alpha2, :city_id, :city_name, :venue_name
  validates_inclusion_of :visible, in: VISIBLE_OPTIONS
      #validates_associated :venue, :message => 'This venue is invalid'

  validates_length_of :price, :maximum => 10, :allow_blank => true

  # Don't let dates be past dates
  validate :date_actual_or_future
  def date_actual_or_future
    if self.date
      if self.date < Date.today
        self.errors.add(:date, I18n.t('activerecord.models.show.errors.past_date'))
      elsif self.date > 1.years.from_now
        self.errors.add(:date, I18n.t('activerecord.models.show.errors.distant_date'))
      end
    end
  end

  #Check if the combination of country, district and city are valid. If javascript has some error, it can happen!
  validate :check_country_district_city_combination
  def check_country_district_city_combination
    if !self.country_alpha2.blank? or self.district_alpha2 or self.city_id
      if !Country[self.country_alpha2] #First check for country
        self.errors.add(:country_alpha2, I18n.t('activerecord.models.show.errors.invalid_country'))
      else #Then check for district
        if !(Country[self.country_alpha2].states.include? self.district_alpha2)
          self.errors.add(:district_alpha2, I18n.t('activerecord.models.show.errors.invalid_district'))
        else #Then check for city
          if !City.from_country(self.country_alpha2).from_district(self.district_alpha2).exists?(self.city_id)
            self.errors.add(:city_id, I18n.t('activerecord.models.show.errors.invalid_city'))
          end
        end
      end
    else
      self.errors.add(:country_alpha2, I18n.t('activerecord.models.show.errors.invalid_country'))
    end
  end

  #  onDestroy:
  #    - destroy subcategory_voter
  #    - destroy

  before_validation do #probable change to before_validation
    #Determine which are the country, district and city of the codes
    if self.city_id.is_a? Numeric
      self.city_name = City.find(self.city_id).name
    end

    #Only apply the denormalization over the venue, IF the venue is public. Otherwise it must be the responsability of the crawler itself
    if(self.venue and self.venue.visible)
      venue = Venue.find(self.venue_id)
      self.venue_name = venue.name if self.venue_name.blank?
      self.venue_website = venue.website if self.venue_website.blank?
      if self.venue_icon.blank?
        self.venue_icon = !venue.external_icon.nil? ? venue.external_icon : venue.icon.url
      end
    end
  end

  # Try building a slug based on the following fields in increasing order of specificity.
  def slug_candidates
    [
        :name,
        [:city_name, :name],
        [:district_name, :city_name, :name],
        [:country_name, :district_name, :city_name, :name]
    ]
  end
  def city_name
    self.city.try(:name)
  end
  def district_name
    self.city.district_name if self.city
  end
  def country_name
    self.city.country_name if self.city
  end


end

app/controllers/shows_controller.rb
class ShowsController < ApplicationController
  include ApplicationHelper
  #before_action :set_show, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource except: [:filters_state, :set_visible]
  skip_load_resource :only => :create

  private
  def fetch_shows_list
    #Set session parameters
    session[:country] = params[:country] || requestCountry
    session[:district] = params[:district] unless params[:district].nil?
    session[:category_id] = params[:category_id] # || Category::DEFAULT_CATEGORY
    session[:show_all_shows] = params[:show_all_shows] unless params[:show_all_shows].nil?

    #session[:show_all_shows] = false

    #p "session[:country]:#{session[:country]}"
    #p "session[:district]:#{session[:district]}"
    #p "session[:category_id]:#{session[:category_id]}"

    country = session[:country]
    district = session[:district]
    category_id = session[:category_id]

    @showList = Show.where("DATE(date) >= ?", Time.zone.now.beginning_of_day).order(city_name: :asc).order(trust: :desc).order(date: :asc).page(params[:page]).per_page(30)
    if !country.blank?
      #Apply country
      @showList = @showList.from_country(country)
      #Apply district
      @showList = @showList.from_district(district) if !district.blank?
      puts "Cnt: #{@showList.count} district: #{district} country: #{country}"
    end
    #Apply category
    if category_id
      @showList = @showList.where(category_id: category_id)
    end
    #Apply visible
    if !user_signed_in? or !current_user.admin?
      @showList = @showList.where(visible: Show::VISIBLE_YES)
    else #admin options
      @showList = @showList.where("visible > ?", Show::VISIBLE_IGNORE)
      @decision_pending_count = Show.where(visible: Show::VISIBLE_DONT_KNOW).count

      session[:view_undecided] = params[:view_undecided] unless params[:view_undecided].nil?
      #p "Session[:view_undecided]: #{session[:view_undecided]}"
      @view_undecided_option = session[:view_undecided] == 'true'
      if @view_undecided_option
        @showList = @showList.where(visible: Show::VISIBLE_DONT_KNOW)
      end
    end

    @showList = @showList || []

  end

  public
  # GET /shows
  # GET /shows.json
  def index
    #@showLength = Show.count
    @showList = fetch_shows_list
    @showLength = @showList.size
    @venues_list = Venue.all
    @remoteCountry = requestCountry()
  end

  def reload_shows
    @showList = fetch_shows_list
    respond_to do |format|
      format.js
    end
  end

  def reload_suggestion
    @country = params[:country]
    @district_name = Country[params[:country]].states[params[:district]]['name']
    @district_alpha2 = params[:district]
    respond_to do |format|
      format.js
    end
  end

  # GET /shows/1
  # GET /shows/1.json
  def show
  end

  # GET /shows/new
  def new
    @show = Show.new(country_alpha2: current_user.country_alpha2,
                     district_alpha2: current_user.district_alpha2,
                     city_id: current_user.city_id)
  end

  # GET /shows/1/edit
  def edit
  end

  # POST /shows
  # POST /shows.json
  def create
    @show = Show.new(show_params)
    @show.user = current_user
    respond_to do |format|
      if @show.save
        format.html { redirect_to @show, notice: 'Show was successfully created.' }
        format.json { render action: 'show', status: :created, location: @show }
      else
        format.html { render action: 'new' }
        format.json { render json: @show.errors, status: :unprocessable_entity }
      end
    end
    p @show.errors.inspect
  end

  # PATCH/PUT /shows/1
  # PATCH/PUT /shows/1.json
  def update
    respond_to do |format|
      if @show.update(show_params)
        format.html { redirect_to @show, notice: 'Show was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @show.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /shows/:show_id/set_visible
  # PATCH/PUT /shows/:show_id/set_visible.json
  def set_visible
    @show = Show.find(params[:show_id])
    authorize! :set_visible, @show # Cancan custom function

    @show.update(show_params)
    respond_to do |format|
     format.js
    end
  end

  # DELETE /shows/1
  # DELETE /shows/1.json
  def destroy
    @show.destroy
    respond_to do |format|
      format.html { redirect_to shows_url }
      format.json { head :no_content }
    end
  end

  #GET filters_state
  #This function is requested by the JS map to synchronize with the selected options
  def filters_state
    respond_to do |format|
      format.json { }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_show
      @show = Show.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def show_params
      params.require(:show).permit(:visible,
                                   :name,
                                   :date,
                                   :country_alpha2, :district_alpha2, :city_id, :city_name,
                                   :venue_id, :venue_name,
                                   :artist_id,
                                   :description, :photo_url, :price, :photo)
    end
end

app/helpers/shows_helper.rb
module ShowsHelper

  def get_unique_show_venues
    Venue.pluck(:id, :name)
  end

  def favouriteCategoriesList
    @show.subcategory_votes.joins(:subcategory).select('name, subcategory_id, sum(amount) as value').group('subcategory_id').order('value DESC').limit(4)
  end

  def remainingCategoriesList(exceptList)
    @categories_subcategories = Subcategory.select('categories.id as category_id, categories.name as category_name, subcategories.id as subcategory_id, subcategories.name as subcategory_name').joins('LEFT OUTER JOIN categories ON subcategories.category_id = categories.id').order('category_name ASC', 'subcategory_name ASC')
    #Now remove the favourite ones from the complete list
    exceptList.each do |favouriteCat|
      @categories_subcategories.each_with_index do |cat_item, i|
        if favouriteCat.subcategory_id == cat_item.subcategory_id
          puts "removing favourites #{cat_item.subcategory_name} from category list"
          @categories_subcategories.to_a.delete_at(i)
          break
        end
      end
    end
    @categories_subcategories
  end

  def complaintsList
    complaintsList = @show.show_votes.where(vote_type: [ShowVote::TYPE_COMPLAINT_WRONG_INFO, ShowVote::TYPE_COMPLAINT_SPAM, ShowVote::TYPE_COMPLAINT_ABUSE ]).select('vote_type, sum(amount) as count').group('vote_type').order('count DESC')
    complaintsList.to_a.delete_if do |complaint|
      if(complaint['count'] < ShowVote::COMPLAINT_SHOW_THRESHOLD)
        true
      end
    end
  end

  def attending_badge(show)
    if show.attending >= ShowVote::GREEN_EVENT_ATTENDANCE_LEVEL
      'badge-success'
    elsif show.attending >= ShowVote::BLUE_EVENT_ATTENDANCE_LEVEL
      'badge-info'
    else
      ''
    end
  end

  def show_line_class(show)
    case show.visible
      when Show::VISIBLE_DONT_KNOW
        'alert-danger'
      when Show::VISIBLE_NO
        'alert-info'
    end
  end

  def show_untrusted_shows
    session[:show_all_shows] || false
  end

end

app/views/shows/_form.html.erb
<%= simple_form_for(@show, :html => { :class => 'form-horizontal', :multipart => true }) do |f| %>
    <%= f.error_notification %>

    <div class="container-fluid">
      <div class="row-fluid">
        <div class="col-md-4 text-center">
          <%= image_tag @show.photo.url %>
          <%= f.file_field :photo %>
        </div>
        <div class="col-md-6">
          <% if current_user.admin? %>
            <div class="form-inputs">
              <div class="checkbox">
                <%= f.input :visible, :collection => {I18n.t('simple_form.yes') => Show::VISIBLE_YES, I18n.t('simple_form.no') => Show::VISIBLE_NO, I18n.t('simple_form.dont_know') => Show::VISIBLE_DONT_KNOW} %>
              </div>
            </div>
          <% end %>

          <%= f.input :name, :required => true %>
          <%= f.input :description, as: :text %>
          <%= f.input :date do %>
            <div class="input-group date">
              <%= f.text_field :date, 'data-behaviour' => 'datetimepicker', value: @show.date, class: 'form-control', :disabled => false %>
                  <span class="input-group-addon"><span class="glyphicon glyphicon-calendar"></span></span>
            </div>
          <% end %>

          <%= f.input :country_alpha2 do %>
            <%= f.select :country_alpha2, options_for_select(available_countries.map {|c| [c.name, c.alpha2]}.insert(0, ''), @show.country_alpha2), {}, { id:'cb_generic_country', class:'form-control' } %>
          <% end %>
          <%= f.input :district_alpha2 do %>
            <%= f.select :district_alpha2, options_for_select((Country[@show.country_alpha2]? (Country[@show.country_alpha2].states.map {|c| [c[1]['name'], c[0]]}):{}), @show.district_alpha2), {}, { id:'cb_generic_district', class:'form-control', include_blank: true } %>
          <% end %>
          <%= f.input :city_id do %>
            <%= f.select :city_id, options_for_select(City.from_country(@show.country_alpha2).from_district(@show.district_alpha2).map {|c| [c.name, c.id]}, @show.city_id), {}, { :id => 'cb_generic_city', class:'form-control', include_blank: true } %>
          <% end %>
          <%= f.input :venue_name %>
            <% #f.select :venue_id, options_for_select(Venue.from_city(@show.city_id).map {|v| [v.name, v.id]}, @show.venue_id), {}, { :id => 'cb_generic_venue', include_blank: true }
            %>

          <%= f.input :price %>
          <br/>
          <%= f.button :submit, class: 'btn btn-primary' %>
        </div>
      </div>
    </div>


<% end %>

app/views/shows/edit.html.erb
<h2><%= "#{I18n.t('helpers.links.edit')} #{I18n.t('activerecord.models.show.one')}" %> </h2>

<%= render 'form' %>

<%= link_to I18n.t('helpers.links.show'), @show %>

app/views/shows/index.html.erb
<% content_for :head do %>
    <meta property="fb:app_id" content="<%= Showgeeks::FACEBOOK_APP_ID %>" />
    <meta property="og:type"   content="article" />
    <meta property="og:site_name" content="Showgeeks" />
    <meta property="og:url"    content="<%= root_url %>" />
    <meta property="og:title"  content="<%= I18n.t('shows.ograph_general_title') %>"/>
    <meta property="og:description" content="<%= I18n.t('shows.ograph_general_description') %>" />
    <meta property="og:image" content='' />
<% end %>

<div class="col-md-8 col-lg-9">
  <div id="div_regionSuggestion" class='alert alert-info' style="display: none">
  </div>

  <div id="div_showList">
    <%= render :partial => 'shows/lists/show_list', :locals => {showList: nil} %>
  </div>
</div>

<div class="col-md-4 col-lg-3" style="min-width: 275px">
   <p class="text-center">
      <%= link_to I18n.t('shows.create_event'), (can? :create, Show) ? new_show_path : new_user_session_path, class: 'btn btn-primary', style: 'width: 120px' %>
   </p>

  <% if can? :manage, Venue %>
      <div class="well">
        <h4 class="text-center">Admin panel</h4>
        <% if current_user and current_user.admin? %>
          <p class="bg-primary text-center"><strong><%= @decision_pending_count %></strong> events pending decision</p>
          <% if @view_undecided_option == true %>
            <%= link_to root_path(view_undecided: false) do %>
               <p class="bg-danger">
                <input type="checkbox" checked> undecided shows only</input>
               </p>
            <% end %>
          <% else %>
            <%= link_to root_path(view_undecided: true) do %>
                <input type="checkbox"> undecided shows only</input>
            <% end %>
          <% end %>
        <% end %>
        <h5>Venues</h5>
        <% @venues_list.each do |venue| %>
            <p><%= link_to venue.name, country_district_city_venue_path(venue.city.country_alpha2, venue.city.district_alpha2, venue.city_id, venue) %></p>
        <% end %>
        <%= render partial: 'crawlers/new_fb_venue' %>
      </div>
  <% end %>

  <div class="sidebar-nav">
    <%= render "maps/map" %>
  </div><!--/.well -->
  <div class="text-center">
    <%= link_to I18n.t('activerecord.models.contact.other'), contacts_path %>
    <!-- ·
    <%= #link_to I18n.t('privacy'), privacy_path
    %>
    ·
    <%= #link_to I18n.t('terms'), terms_path
  %> -->
  </div>
</div><!--/span-->

app/views/shows/index.js.erb
$('#shows_table').append('<%= j render :partial => 'shows/lists/show_list_contents', :locals => {showList: @showList} %>');
<% if @showList.next_page %>
    $('.pagination').replaceWith('<%= j will_paginate(@showList) %>');
<% else %>
    $('.pagination').remove();
<% end %>

app/views/shows/new.html.erb
<h2><%= "#{I18n.t('helpers.links.new')} #{I18n.t('activerecord.models.show.one')}" %> </h2>

<%= render 'form' %>

<%= link_to I18n.t('helpers.links.back'), shows_path %>

app/views/shows/reload_shows.js.erb
$('#div_showList').hide();
$('#div_showList').html("<%= j render :partial => 'shows/lists/show_list', :locals => {showList: @showList} %>");
$('#div_categories_filter').html("<%= j render :partial => 'layouts/filters/show_category_filter', :locals => {showList: @showList} %>");

    //This is not necessary!
    //$('#cb_country').trigger("change", '<%= session[:country] %>');
    //$('#cb_district').val('<%= session[:district] %>');
    //$('#country_map').js_map('selectRegion', '<%= session[:district] %>')

$('#div_showList').fadeIn();

app/views/shows/reload_suggestion.js.erb
$("#div_regionSuggestion").html("<%= j render :partial => 'shows/lists/show_suggestion', :locals => {district_name: @district_name, district_alpha2: @district_alpha2} %>");
$('#div_regionSuggestion').show('slide');

app/views/shows/set_visible.js.erb
$('#show_checkbox_<%= @show.id %>').html('<%= j render :partial => 'shows/lists/visible_checkbox', :locals => {item: @show} %>');
$('#ignore_checkbox_<%= @show.id %>').html('<%= j render :partial => 'shows/lists/ignore_show_checkbox', :locals => {item: @show} %>');

// if hidden state, then remove the element from the list
<% if @show.visible == Show::VISIBLE_IGNORE %>
  $('#show_list_item<%= @show.id %>').html('')
<% end %>

app/views/shows/show.html.erb
<% content_for :head do %>
    <meta property="fb:app_id" content="<%= Showgeeks::FACEBOOK_APP_ID %>" />
    <meta property="og:type"   content="article" />
    <meta property="og:site_name" content="Showgeeks" />
    <meta property="og:url"    content="<%= show_url(@show) %>" />
    <meta property="og:title"  content="<%= "#{@show.name} - #{@show.city_name}" %>" />
    <meta property="og:description" content="<%= @show.description.empty? ? ("#{@show.name} - #{@show.city_name}") : @show.description %>" />
    <meta property="og:image"  content=<%= @show.photo_url %> />
<% end %>

<p id="notice"></p>

<div class="col-sm-offset-1 col-md-10">
  <div id="participants_votes" class="pull-right">
    <%= render partial: 'shows/votes/attending_votes' %>
  </div>
    <p>
      <h3>
        <%= link_to_if @show.artist, @show.name, @show.artist %>
      </h3>
    </p>

    <p>
    <div class="row-fluid">
        <span id="div_participants_info_label">
          <%= render 'shows/votes/attending_info' %>
        </span>
        ·
        <%= link_to "<fb:comments-count href=#{show_url(@show)}></fb:comments-count> ".html_safe + I18n.t('shows.show.comments'), :anchor => 'comments' %>
    </div>
    </p>
    <p>
      <strong><%= I18n.t('simple_form.labels.show.venue_name') %>:</strong>
      <% if @show.venue and @show.venue.visible %>
        <%= link_to @show.venue_name, country_district_city_venue_path(@show.country_alpha2, @show.district_alpha2, @show.city_id, @show.venue) %>
      <% else %>
          <%= @show.venue_name %>
      <% end %>
      <%= "@ #{@show.city_name}" %>
      <%= "- #{Country[@show.country_alpha2].states[@show.district_alpha2]['name']}" if show_state(@show.country_alpha2) %>
    </p>
    <p>
      <strong><%= I18n.t('simple_form.labels.show.date') %>:</strong>
      <% if @show.is_date_only %>
         <%= local_time(@show.date, '%B %e, %Y') %>, --:--
      <% else %>
          <%= local_time(@show.date, '%B %e, %Y, %H:%M') %>
      <% end %>
    </p>

    <p>
      <strong><%= I18n.t('simple_form.labels.show.price') %>:</strong>
      <%= @show.price unless !@show.price %>
    </p>
    <p>
      <strong><%= I18n.t('simple_form.labels.show.categories') %>:</strong>
      <div id="categories_error_notifier"></div>
      <div id="div_categories">
        <%= render partial: 'shows/votes/subcategory_votes' %>
      </div>
    </p>

    <div id="div_complaints">
      <%= render partial: 'shows/votes/warning_votes' %>
    </div>

    <% if @show.description or @show.photo_url or @show.photo %>
        <div>
          <table>
            <tbody>
                <tr>
                  <td width='200' align="center">
                      <% if @show.photo_url %>
                        <%= image_tag @show.photo_url %>
                      <% else %>
                        <%= image_tag @show.photo.url(:medium) %>
                      <% end %>
                  </td>
                  <td style="padding:10px 10px 10px 10px; vertical-align:top">
                    <% if !@show.description.blank? %>
                      <%= @show.description.html_safe %>
                    <% else %>
                        <p class="help-block"><%= I18n.t('shows.show.no_info_available') %></p>
                    <% end %>
                    <% if @show.url %>
                      <%= link_to I18n.t('shows.show.plus_info'), @show.url, target: '_blank' %>
                    <% end %>
                  </td>
                </tr>
            </tbody>
          </table>
        </div>
    <% end %>
    <br/>
    <br/>
      <ul class="social-share-list list-inline" >
        <li class='fb'>
          <%= like_button Showgeeks::FACEBOOK_APP_ID,
                          action: 'like',
                          layout: :box_count,
                          share: false,
                          href: show_url(@show)
          %>
        </li>
        <li class='gp'>
          <%= google_plus_button href: show_url(@show),
                                 script: true,
                                 layout: :box_count,
                                 annotations: :bubble,
                                 size: :tall
          %>
        </li>
        <li class='twt'>
          <%= tweet_button count: 'vertical',
                           text: "#{@show.name} @ #{@show.city_name}",
                           url: show_url(@show),
                           via: 'theshowgeeks' #Twitter account handler
          %>
        </li>
      </ul>
  <hr/>

  <a id="comments">
   <div class="fb-comments" data-href="<%= show_url(@show) %>" data-numposts="10" data-colorscheme="light"></div>
  </a>
  <div class="col-md-12 col-lg-12">
    <% if can? :edit, @show %>
      <%= link_to I18n.t('helpers.links.edit'), edit_show_path(@show) %> |
    <% end %>
    <%= link_to I18n.t('helpers.links.back'), root_path %>
    <div class="pull-right">
      <% if user_signed_in? %>
        <div id='div_denounceButton'>
          <%= render partial: 'shows/votes/denounce_button' %>
        </div>
      <% else %>
        <%= link_to I18n.t('shows.show.report.report'), new_user_session_path %>
      <% end %>
    </div>
  </div>
</div>